### ISSUE TITLE
商品号从哪里看？

### ISSUE THREAD

**Issue by rekcah1986** [maoxs2/MiBuy#8]
rt

**Comment by c0mm4nd** [comment]
I have read the script thrice but I still cannot find where it requires a goods id...

If you mean the `itemlink`, just input the goods URL.

**Comment by rekcah1986** [comment]
可能是1元抢购不一样，既看不到productId，没到时间之前也不会跳转

**Comment by c0mm4nd** [comment]
You mean https://www.mi.com/buy/seckill ?

**Comment by rekcah1986** [comment]
是的，上次我是1元秒杀手机的时候发现找不到productId，回头有1元商品的时候可以再关注下

**Comment by c0mm4nd** [comment]
There are 2 suggestions about this circumstance:

1. simulate a human view the page and click from the index page, in puppeteer.
2. use userscript and do more manually.
